import React, { useMemo } from 'react';
import { X, Moon, MessageSquare, TrendingUp, Calendar, DollarSign, CheckCircle2, AlertCircle, Copy } from 'lucide-react';
import { getLocalYYYYMMDD } from '../../utils/slots';

export default function EODSummaryModal({
  isOpen,
  onClose,
  transactions = [],
  bookings = [],
  shiftHandovers = [],
  currentUser
}) {
  if (!isOpen) return null;

  const todayStr = getLocalYYYYMMDD();

  // Compute Today's Stats
  const todayStats = useMemo(() => {
    // Today's Bookings
    const todayBookings = bookings.filter(b => b.date === todayStr && b.status !== 'canceled');
    const courtMatchesCount = todayBookings.length;
    const totalPlayMins = todayBookings.reduce((sum, b) => sum + (Number(b.duration) || 0), 0);
    const totalPlayHours = (totalPlayMins / 60).toFixed(1);

    // Today's Transactions
    const todayTxs = transactions.filter(t => {
      const txDate = t.date ? t.date.slice(0, 10) : '';
      return txDate === todayStr;
    });

    let totalCourtIncome = 0;
    let totalAcademyIncome = 0;
    let totalBeverageIncome = 0;
    let totalPassIncome = 0;
    let totalExpenses = 0;
    let cashIncome = 0;
    let upiIncome = 0;
    let turftownIncome = 0;

    todayTxs.forEach(t => {
      const amt = Number(t.amount) || 0;
      if (t.type === 'income') {
        if (t.category?.includes('Court')) totalCourtIncome += amt;
        else if (t.category?.includes('Academy') || t.category?.includes('Fee')) totalAcademyIncome += amt;
        else if (t.category?.includes('Beverage')) totalBeverageIncome += amt;
        else if (t.category?.includes('Pass') || t.category?.includes('Wallet')) totalPassIncome += amt;
        else totalCourtIncome += amt;

        if (t.paymentMode === 'cash') cashIncome += amt;
        else if (t.paymentMode === 'upi') upiIncome += amt;
        else if (t.paymentMode === 'turftown') turftownIncome += amt;
      } else if (t.type === 'expense') {
        totalExpenses += amt;
      }
    });

    const grossRevenue = totalCourtIncome + totalAcademyIncome + totalBeverageIncome + totalPassIncome;
    const netTakeHome = grossRevenue - totalExpenses;

    // Today's Shift Handovers
    const todayHandovers = shiftHandovers.filter(s => s.date === todayStr);

    return {
      courtMatchesCount,
      totalPlayHours,
      grossRevenue,
      totalCourtIncome,
      totalAcademyIncome,
      totalBeverageIncome,
      totalPassIncome,
      totalExpenses,
      cashIncome,
      upiIncome,
      turftownIncome,
      netTakeHome,
      todayHandovers
    };
  }, [transactions, bookings, shiftHandovers, todayStr]);

  const generateReportText = () => {
    return [
      `🐼 *PANDA SPORTS ACADEMY — DAILY REVENUE CLOSE*`,
      `📅 *Date:* ${todayStr}`,
      `👤 *Report Generated By:* ${currentUser?.name || 'Staff Manager'}`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `🏸 *Court Operations:*`,
      `  • Total Matches: ${todayStats.courtMatchesCount}`,
      `  • Court Time Played: ${todayStats.totalPlayHours} Hours`,
      `  • Court Collections: ₹${todayStats.totalCourtIncome.toLocaleString()}`,
      ``,
      `🥋 *Academy Classes:* ₹${todayStats.totalAcademyIncome.toLocaleString()}`,
      `🥤 *Beverages & Rentals:* ₹${todayStats.totalBeverageIncome.toLocaleString()}`,
      `🎟️ *Wallet / Passes Sold:* ₹${todayStats.totalPassIncome.toLocaleString()}`,
      `💸 *Operational Expenses:* -₹${todayStats.totalExpenses.toLocaleString()}`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `💰 *GROSS DAY REVENUE:* ₹${todayStats.grossRevenue.toLocaleString()}`,
      `💵 *NET DAY CLOSE:* ₹${todayStats.netTakeHome.toLocaleString()}`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `💳 *COLLECTION BY PAYMENT MODE:*`,
      `  • 💵 Cash in Counter: ₹${todayStats.cashIncome.toLocaleString()}`,
      `  • 📱 UPI / GPay: ₹${todayStats.upiIncome.toLocaleString()}`,
      `  • 🌐 TurfTown Online: ₹${todayStats.turftownIncome.toLocaleString()}`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      todayStats.todayHandovers.length > 0 
        ? `✅ *Shift Handovers Completed:* ${todayStats.todayHandovers.map(h => `${h.shiftName} (${h.outgoingStaff} → ${h.takingOverStaff})`).join(', ')}`
        : `⚠️ *Shift Handovers:* Counter audit pending`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      `🎾 *Panda Sports Academy Management System*`
    ].join('\n');
  };

  const handleSendWhatsApp = () => {
    const text = generateReportText();
    window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer');
  };

  const handleCopyText = () => {
    const text = generateReportText();
    navigator.clipboard.writeText(text);
    alert("Daily EOD report copied to clipboard!");
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl w-full max-w-lg shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="px-6 py-4 border-b border-zinc-100 flex justify-between items-center bg-gradient-to-r from-zinc-900 via-zinc-950 to-purple-950 text-white shrink-0">
          <div className="flex items-center gap-2">
            <Moon className="text-amber-400" size={22} />
            <div>
              <h3 className="font-extrabold text-sm text-white flex items-center gap-1.5">
                End-of-Day (EOD) Director Close
                <span className="text-[10px] bg-amber-400/20 text-amber-300 px-2 py-0.5 rounded-full font-black">
                  10:00 PM Audit
                </span>
              </h3>
              <p className="text-[10px] text-zinc-400">Date: {todayStr} • Summary for Academy Director</p>
            </div>
          </div>
          <button onClick={onClose} className="text-zinc-400 hover:text-white p-1">
            <X size={20} />
          </button>
        </div>

        {/* Report Content */}
        <div className="p-6 space-y-4 overflow-y-auto">
          {/* Top Revenue Highlight */}
          <div className="bg-gradient-to-br from-emerald-500 to-emerald-700 text-white p-4 rounded-2xl shadow-sm flex justify-between items-center">
            <div>
              <span className="text-xs font-bold uppercase tracking-wider text-emerald-100 block">
                Today's Gross Collections
              </span>
              <h2 className="text-2xl font-black">₹{todayStats.grossRevenue.toLocaleString()}</h2>
              <p className="text-[11px] text-emerald-100 mt-0.5">
                Net Take-Home (after ₹{todayStats.totalExpenses} expenses): <strong>₹{todayStats.netTakeHome.toLocaleString()}</strong>
              </p>
            </div>
            <div className="text-right">
              <span className="text-[10px] font-black uppercase tracking-wider bg-white/20 px-2 py-1 rounded-lg">
                {todayStats.courtMatchesCount} Matches
              </span>
              <p className="text-xs font-bold text-emerald-100 mt-1">{todayStats.totalPlayHours} hrs played</p>
            </div>
          </div>

          {/* Revenue Stream Breakdown */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-600">
              Departmental Breakdown
            </h4>
            <div className="grid grid-cols-2 gap-2 text-xs font-semibold">
              <div className="bg-zinc-50 p-2.5 rounded-xl border border-zinc-200 flex justify-between items-center">
                <span className="text-zinc-600">🏸 Court Bookings:</span>
                <span className="font-extrabold text-zinc-900">₹{todayStats.totalCourtIncome.toLocaleString()}</span>
              </div>
              <div className="bg-zinc-50 p-2.5 rounded-xl border border-zinc-200 flex justify-between items-center">
                <span className="text-zinc-600">🥋 Academy Fees:</span>
                <span className="font-extrabold text-zinc-900">₹{todayStats.totalAcademyIncome.toLocaleString()}</span>
              </div>
              <div className="bg-zinc-50 p-2.5 rounded-xl border border-zinc-200 flex justify-between items-center">
                <span className="text-zinc-600">🥤 POS & Rentals:</span>
                <span className="font-extrabold text-zinc-900">₹{todayStats.totalBeverageIncome.toLocaleString()}</span>
              </div>
              <div className="bg-zinc-50 p-2.5 rounded-xl border border-zinc-200 flex justify-between items-center">
                <span className="text-zinc-600">🎟️ Passes & Wallets:</span>
                <span className="font-extrabold text-zinc-900">₹{todayStats.totalPassIncome.toLocaleString()}</span>
              </div>
            </div>
          </div>

          {/* Payment Mode Cash vs Online */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-600">
              Cash Drawer vs Digital Collections
            </h4>
            <div className="grid grid-cols-3 gap-2 text-xs text-center">
              <div className="bg-emerald-50 p-2.5 rounded-xl border border-emerald-200">
                <span className="text-[10px] font-bold uppercase text-emerald-800 block">Cash in Drawer</span>
                <span className="text-sm font-black text-emerald-900">₹{todayStats.cashIncome.toLocaleString()}</span>
              </div>
              <div className="bg-blue-50 p-2.5 rounded-xl border border-blue-200">
                <span className="text-[10px] font-bold uppercase text-blue-800 block">UPI / GPay</span>
                <span className="text-sm font-black text-blue-900">₹{todayStats.upiIncome.toLocaleString()}</span>
              </div>
              <div className="bg-purple-50 p-2.5 rounded-xl border border-purple-200">
                <span className="text-[10px] font-bold uppercase text-purple-800 block">TurfTown</span>
                <span className="text-sm font-black text-purple-900">₹{todayStats.turftownIncome.toLocaleString()}</span>
              </div>
            </div>
          </div>

          {/* Shift Handover Status */}
          <div className="p-3 bg-zinc-50 rounded-xl border border-zinc-200 flex items-center justify-between text-xs">
            <span className="font-bold text-zinc-700">Staff Shift Handover Audit:</span>
            {todayStats.todayHandovers.length > 0 ? (
              <span className="text-[10px] font-black uppercase text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded-full flex items-center gap-1">
                <CheckCircle2 size={12} /> {todayStats.todayHandovers.length} Shift(s) Reconciled
              </span>
            ) : (
              <span className="text-[10px] font-black uppercase text-amber-700 bg-amber-100 px-2 py-0.5 rounded-full flex items-center gap-1">
                <AlertCircle size={12} /> Handover Pending
              </span>
            )}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-zinc-100 bg-zinc-50 flex items-center gap-2 shrink-0">
          <button
            type="button"
            onClick={handleCopyText}
            className="py-2.5 px-3 rounded-xl border border-zinc-300 text-zinc-700 font-bold text-xs hover:bg-white flex items-center gap-1.5 transition-colors"
          >
            <Copy size={14} /> Copy
          </button>
          <button
            type="button"
            onClick={handleSendWhatsApp}
            className="flex-1 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs flex items-center justify-center gap-2 shadow-md transition-all"
          >
            <MessageSquare size={16} /> Send EOD Report to Director on WhatsApp
          </button>
        </div>
      </div>
    </div>
  );
}
